### ISSUE TITLE
Possible error in FedAvgM implementation

### ISSUE THREAD

**Issue by Zilinghan** [APPFL/APPFL#129]
In `server_federated.py`, the `update_m_vector` is defined as follows:

`def update_m_vector(self):
        for name, _ in self.model.named_parameters():
            self.m_vector[name] = (
                self.server_momentum_param_1 * self.m_vector[name]
                + (1.0 - self.server_momentum_param_1) * self.pseudo_grad[name]
            )`

However, according to the FedAvgM paper https://arxiv.org/pdf/1909.06335.pdf Section 4.2, it is supposed to be `v=beta*v+dw` instead of `v=beta*v+(1-beta)*dw`

Could anyone help to check on this?

**Comment by minseok-ryu** [comment]
@Zilinghan In my opinion, that is just a different way of assigning weight (importance) on the current "dw" versus historically accumulated sum of "dw"s. You can find ``v=beta*v+(1-beta)*dw`` from many other places (e.g., see ``https://arxiv.org/pdf/2003.00295.pdf`` or ``https://towardsdatascience.com/stochastic-gradient-descent-with-momentum-a84097641a5d``

**Comment by Zilinghan** [comment]
@minseok-ryu Hi Minseok, I recently used FedAvgM in one application, and if I use `v=beta*v+dw`, I can get 97% accuracy quickly, but if I use `v=beta*v+(1-beta)*dw`, the algorithm only converges at around 73%.

**Comment by Zilinghan** [comment]
That's also possible. Let me try some other examples and also do some investigations.

**Comment by Zilinghan** [comment]
resolved in refactor
