### ISSUE TITLE
Race condition when creating directory

### ISSUE THREAD

**Issue by Zilinghan** [APPFL/APPFL#133]
File "/u/zl52/projects/APPFL/src/appfl/misc/utils.py", line 82, in create_custom_logger
    os.mkdir(dir)
FileExistsError: [Errno 17] File exists: './outputs_ISIC2019_ServerFedCPASAvgNew_20'

In the `misc/utils.py`,https://github.com/APPFL/APPFL/blob/ab4778200c2262294f45c3e4420ed174286fc3d0/src/appfl/misc/utils.py#LL49C1-L50C22 it is possible that two MPI processes create the same directory at the same time. Namely, two processes both check `if os.path.isdir(dir) == False:` and they are both calling os.mkdir.
Maybe we need to add a lock or just let process 0 do that.

**Comment by yim0331** [comment]
I also had a similar issue while downloading the test data. This is my solution: https://github.com/APPFL/APPFL/blob/17c052f3e4941a51c2882c227d3726700c223483/tests/test_mnist.py#L93-L116

The basic idea is that only the rank 0 processes handle the file system to avoid the race condition. In my case, the folder and files are necessary for all other processes, so I hold all non-zero rank processes to complete the file system operation by comm.Barrier() function.

I hope this is a useful comment.
