### ISSUE TITLE
Release minor v0.3.0

### ISSUE THREAD

**Issue by Zilinghan** [APPFL/APPFL#146]
I think we are ready to release a minor v0.3.0 after adding more authors for the following two places.
https://github.com/APPFL/APPFL/blob/fd87aa84fa8176af2de1cc8d211c277834f85a53/setup.py#L4
https://github.com/APPFL/APPFL/blob/fd87aa84fa8176af2de1cc8d211c277834f85a53/CITATION.cff#L12

**Comment by madduri** [comment]
Leave a comment here?

**Comment by yim0331** [comment]
My information is here:

"Sang-il Yim": "yim@anl.gov",

given-names: Sang-il
family-names: Yim
email: yim@anl.gov
affiliation: Argonne National Laboratory

**Comment by Zilinghan** [comment]
I updated the author information to the following two files:
https://github.com/APPFL/APPFL/blob/fd87aa84fa8176af2de1cc8d211c277834f85a53/setup.py
https://github.com/APPFL/APPFL/blob/fd87aa84fa8176af2de1cc8d211c277834f85a53/CITATION.cff
Now I think we are ready for releasing v0.3.0
@kibaekkim Could you please add me to the appfl project for releasing, my PyPI username is Zilinghan

**Comment by kibaekkim** [comment]
@shourya01 you should be added as a contributor. Can you please leave your info here too?

@Zilinghan I just added you to the pypi project.

**Comment by Zilinghan** [comment]
I added Shourya with the following info 
- given-names: Shourya
    family-names: Bose
    email: shbose@ucsc.edu
    affiliation: University of California, Santa Cruz

**Comment by shourya01** [comment]
Thanks!
