### ISSUE TITLE
Differential privacy gives error if device is CUDA.

### ISSUE THREAD

**Issue by shourya01** [APPFL/APPFL#150]
**Description:**
Running training with DP gives error when a cuda device is used.

**System specs:**
Conda env with APPFL (built on commit 6237d40), PyTorch 2.0.1. System has NVIDIA Titan RTX GPU with cuda enabled.

**How to replicate:**
`mpiexec -np 3 python /home/L2RPN/APPFL/APPFL/examples/mnist_mpi_sync.py --partition class_noiid --loss_fn losses/celoss.py --loss_fn_name CELoss --num_epochs 10 --clip_grad --clip_value 1 --local_train_pattern epochs --use_dp --epsilon 0.01`
Here, replace `/home/L2RPN/APPFL/APPFL/examples` with your path to examples directory of APPFL.

**Expected output**
Model trains.

**Observed output**
```
-------Loading_Time= 25.679912567138672
-------Loading_Time= 25.750715494155884
-------Loading_Time= 26.831706523895264
Traceback (most recent call last):
  File "/home/L2RPN/APPFL/APPFL/examples/mnist_mpi_sync.py", line 145, in <module>
    main()
  File "/home/L2RPN/APPFL/APPFL/examples/mnist_mpi_sync.py", line 135, in main
    rms.run_client(cfg, comm, model, loss_fn, train_datasets, test_dataset, metric)
  File "/home/L2RPN/APPFL/APPFL/src/appfl/run_mpi_sync.py", line 203, in run_client
    local_model = client.update()
  File "/home/L2RPN/APPFL/APPFL/src/appfl/algorithm/client_optimizer.py", line 82, in update
    super(ClientOptim, self).laplace_mechanism_output_perturb(scale_value)
  File "/home/L2RPN/APPFL/APPFL/src/appfl/algorithm/fl_base.py", line 208, in laplace_mechanism_output_perturb
    self.primal_state[name] += m.sample()
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
Traceback (most recent call last):
  File "/home/L2RPN/APPFL/APPFL/examples/mnist_mpi_sync.py", line 145, in <module>
    main()
  File "/home/L2RPN/APPFL/APPFL/examples/mnist_mpi_sync.py", line 135, in main
    rms.run_client(cfg, comm, model, loss_fn, train_datasets, test_dataset, metric)
  File "/home/L2RPN/APPFL/APPFL/src/appfl/run_mpi_sync.py", line 203, in run_client
    local_model = client.update()
  File "/home/L2RPN/APPFL/APPFL/src/appfl/algorithm/client_optimizer.py", line 82, in update
    super(ClientOptim, self).laplace_mechanism_output_perturb(scale_value)
  File "/home/L2RPN/APPFL/APPFL/src/appfl/algorithm/fl_base.py", line 208, in laplace_mechanism_output_perturb
    self.primal_state[name] += m.sample()
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

**Solution (?)**
Replace `self.primal_state[name] += m.sample()` with `self.primal_state[name] += m.sample().to(self.primal_state[name].device)` in `fl_base.py`.

**Comment by yim0331** [comment]
Hi Shourya,

The problem is that the [self.primal_state values are moved from GPU to CPU](https://github.com/APPFL/APPFL/blob/6237d40b2e00d8fbb6669f191632075e31232202/src/appfl/algorithm/client_optimizer.py#L74C9-L76C66) for the MPI processing after the client update function. 

In this case, when the line, self.primal_state[name] += m.sample() is called, the self.primal_state located in CPU memory while m.sample() is in GPU memory.

The solution will be changing the calling timing of the [client_optimizer.py code line 74-76 ](https://github.com/APPFL/APPFL/blob/6237d40b2e00d8fbb6669f191632075e31232202/src/appfl/algorithm/client_optimizer.py#L74C9-L76C66) after the differential privacy operation (just before return the self.primal_state)

**Comment by Zilinghan** [comment]
Thanks for the catch @shourya01 and suggestion @yim0331. I just pushed changes accordingly here https://github.com/APPFL/APPFL/tree/150-differential-privacy-gives-error-if-device-is-cuda, @shourya01 could you please check if it works, thanks

**Comment by yim0331** [comment]
@Zilinghan The [deep copy code](https://github.com/APPFL/APPFL/blob/f5308971342be68b42e8269f218f3e97c329b60e/src/appfl/algorithm/client_optimizer.py#L73C9-L73C67) should be also moved after the differential privacy operation

**Comment by Zilinghan** [comment]
@shourya01 Does changing the order solve this problem, if so, we could merge the branch to resolve the issue in the main branch

**Comment by shourya01** [comment]
@Zilinghan It does! I think we can merge and close this issue.
