### ISSUE TITLE
ModuleNotFoundError: No module named 'appfl.comm'

### ISSUE THREAD

**Issue by ZeYang1025** [APPFL/APPFL#156]
When I finish installing locally as the doc said and want to try the example, I get an error called `ModuleNotFoundError: No module named 'appfl.comm'`  
Maybe the installation documentation is not correct.

**Comment by Zilinghan** [comment]
I just noticed some issue for the version on PyPI, for now, you could install from source. I will release a patch version asap
`git clone https://github.com/APPFL/APPFL.git
cd APPFL
pip install -e ".[dev,examples,analytics]"`

**Comment by ZeYang1025** [comment]
Thank you! The problem has been solved in the latest version.
