### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by kibaekkim** [APPFL/APPFL#159]
This is the issue for releases. We can reuse this issue whenever we release new version.

**Comment by kibaekkim** [comment]
We need to release new version:
- Add @grantwilkins to the contributor list.
- Update @minseok-ryu 's email address
- Suggested version v0.4.0

**Comment by Zilinghan** [comment]
@kibaekkim Sure! I will add Grant's information and update Minseok's email when making the release. 

I am now working on using APPFL to create a decentralized learning experiment, which can showcase the adaptivity of APPFL. - I will make the release after including this example - tentative plan is the early next week

**Comment by kibaekkim** [comment]
Thanks @Zilinghan for releasing [v0.4.0](https://github.com/APPFL/APPFL/releases/tag/v0.4.0)
