### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by kibaekkim** [APPFL/APPFL#160]
The documentation is missing:
- some algorithms: `iceadmm`, `iiadmm`, `FedAsync`, `FedBuff`, and `FedCompass`
- personalization
- compressions

**Comment by Zilinghan** [comment]
@kibaekkim 
I have added documentations for FedAsync, FedBuf, and FedCompass [here](https://github.com/APPFL/APPFL/blob/main/docs/users/user_implemented_async_algorithm.rst), and updated other documents.

@shourya01 and @minseok-ryu 
You may add PPFL and personalized FL methods in the following two placeholder files.
[PPFL](https://github.com/APPFL/APPFL/blob/main/docs/users/user_implemented_ppfl_algorithm.rst), [PFL](https://github.com/APPFL/APPFL/blob/main/docs/users/user_implemented_pfl_algorithm.rst)

**Comment by kibaekkim** [comment]
Let's get this done.

@minseok-ryu : can you write the privacy algorithm [here](https://github.com/APPFL/APPFL/blob/79bff930bb0f760cd985cbbf7e1f82bda6338b05/docs/users/user_implemented_ppfl_algorithm.rst)?

@shourya01 : can you write the personalization [here](https://github.com/APPFL/APPFL/blob/79bff930bb0f760cd985cbbf7e1f82bda6338b05/docs/users/user_implemented_pfl_algorithm.rst)?

**Comment by kibaekkim** [comment]
Opening separate issues #174 #175 and closing this.
