### ISSUE TITLE
Which communication protocol and serialization method is supported?

### ISSUE THREAD

**Issue by Rene36** [APPFL/APPFL#181]
Dear APPFL Team,

I am currently writing a survey paper on Federated Computing. One part of it describes existing FL frameworks. Could you please let me know which communication protocol (e.g., gRPC, WebSocket, HTTP, GLOO) and serialization method (e.g., Pickle, JSON, Protobuf, FOBS) you supports I already saw in your documentation that you support gRPC, but maybe there is more.

Any help is highly appreciated.

**Comment by kibaekkim** [comment]
I would distinguish "communication protocols" from "communication packages". APPFL supports communication protocols through communication packages gRPC and Globus. Both gRPC and Globus mainly use HTTP with various authentication mechanisms such as SSL/TLS and token-based ones. Globus also uses GridFTP. For serialization method, we support Pickle and Protobuf. In addition, we support the compression (and thus serialization and quantization) through SZ package (https://szcompressor.org).

@grantwilkins @madduri @Zilinghan can correct and/or add more.

**Comment by Zilinghan** [comment]
I think I can clarify this as following. 
1. In the original paper,
``` 
@inproceedings{ryu2022appfl,
  title={APPFL: open-source software framework for privacy-preserving federated learning},
  author={Ryu, Minseok and Kim, Youngdae and Kim, Kibaek and Madduri, Ravi K},
  booktitle={2022 IEEE International Parallel and Distributed Processing Symposium Workshops (IPDPSW)},
  pages={1074--1083},
  year={2022},
  organization={IEEE}
}
```
we only support gRPC, which uses protobuf to serialize objects.
2. In two follow-up works:
```
@inproceedings{li2023appflx,
  title={Appflx: Providing privacy-preserving cross-silo federated learning as a service},
  author={Li, Zilinghan and He, Shilan and Chaturvedi, Pranshu and Hoang, Trung-Hieu and Ryu, Minseok and Huerta, EA and Kindratenko, Volodymyr and Fuhrman, Jordan and Giger, Maryellen and Chard, Ryan and others},
  booktitle={2023 IEEE 19th International Conference on e-Science (e-Science)},
  pages={1--4},
  year={2023},
  organization={IEEE}
}

@article{li2024secure,
  title={Secure Federated Learning Across Heterogeneous Cloud and High-Performance Computing Resources--A Case Study on Federated Fine-tuning of LLaMA 2},
  author={Li, Zilinghan and He, Shilan and Chaturvedi, Pranshu and Kindratenko, Volodymyr and Huerta, Eliu A and Kim, Kibaek and Madduri, Ravi},
  journal={arXiv preprint arXiv:2402.12271},
  year={2024}
}
```
APPFL integrates a new communication package called _[Globus Compute](https://funcx.readthedocs.io/en/latest/quickstart.html)_, which is a function-as-a-service platform, changing each FL client device into an endpoint to execute local training function. In such case, it uses HTTPS for client identity authentication and RabbitMQ for task dispatch. We use dill and pickle for serialization in such case.
3. In addition to those lossless serialization, APPFL also supports lossy serialization (for better communication efficiency) using lossy compressor such as [SZ compression](https://szcompressor.org/) to convert ML model parameters from tensor to bytes, introduced in the following work
```
@article{wilkins2023efficient,
  title={Efficient Communication in Federated Learning Using Floating-Point Lossy Compression},
  author={Wilkins, Grant and Di, Sheng and Calhoun, Jon C and Kim, Kibaek and Underwood, Robert and Cappello, Franck},
  journal={arXiv preprint arXiv:2312.13461},
  year={2023}
}
```

**Comment by Zilinghan** [comment]
By the way, if you would like easier further communication, @Rene36, you could join our [Discord channel](https://discord.com/invite/bBW56EYGUS)

**Comment by Rene36** [comment]
Thanks a lot for the quick and elaborate answers :)
