### ISSUE TITLE
Restructuring the code

### ISSUE THREAD

**Issue by kibaekkim** [APPFL/APPFL#19]
While packing the repo, @madduri found that we would need to restructure the code as suggested in https://packaging.python.org/en/latest/tutorials/packaging-projects/.

**Comment by kibaekkim** [comment]
@markxiao please address this issue.
- create new branch from `main` branch.
- restructure/refactor the code as described in the packaging doc
- test
- create pull request

**Comment by kibaekkim** [comment]
@markxiao so this is not necessary for the code release, correct?

**Comment by markxiao** [comment]
I did need to create a dir such as "src" and move appfl dir into this new directory. Then create two files that is required for building. I was able to build, but we need testing to know if anything needs to be changed inside of appfl dir @kibaekkim

**Comment by kibaekkim** [comment]
@markxiao great. Do you mind if you move your fork to this repo as a separate branch so that we can take a look at it together and merge in the end?
