### ISSUE TITLE
Update examples

### ISSUE THREAD

**Issue by minseok-ryu** [APPFL/APPFL#85]
some examples need to be updated

**Comment by halliday1** [comment]
Here are some issues I'm running into with the examples:
```
python3 cifar10.py 
Traceback (most recent call last):
  File "cifar10.py", line 14, in <module>
    from models.resnet import *
ModuleNotFoundError: No module named 'models.resnet'
```

```
python3 femnist.py 
Traceback (most recent call last):
  File "femnist.py", line 110, in <module>
    main()
  File "femnist.py", line 89, in main
    train_datasets, test_dataset = get_data(comm)
  File "femnist.py", line 30, in get_data
    with open("%s/test/all_data_%s_niid_05_keep_0_test_9.json" % (dir, idx)) as f:
FileNotFoundError: [Errno 2] No such file or directory: '.../APPFL/examples/datasets/RawData/FEMNIST/test/all_data_0_niid_05_keep_0_test_9.json'
```

```
python3 coronahack.py 
Traceback (most recent call last):
  File "coronahack.py", line 88, in <module>
    main()
  File "coronahack.py", line 67, in main
    train_datasets, test_dataset = get_data(comm)
  File "coronahack.py", line 27, in get_data
    with open("%s/all_test_data.json" % (dir)) as f:
FileNotFoundError: [Errno 2] No such file or directory: '.../APPFL/examples/datasets/PreprocessedData/Coronahack_Clients_4/all_test_data.json'
```

**Comment by zachross015** [comment]
The first issue has to do with the fact that the directory `examples/models` was excluded in the `.gitignore` file, so the resnet model isn't included. We updated this in the clean_up branch and added resnet back in, but if this was intentionally excluded then the examples may need to be updated further.

**Comment by minseok-ryu** [comment]
For the issues from the "femnist.py" and "coronahack.py", it seems that you do not have data in the path.

**Comment by samg2003** [comment]
Yeah README in datasets directory explains how to store data, but it’s not explicitly clear to do that in README of examples. README could be little more informative their I think because people would realise they have to store data only after reading the code or getting error.
